apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk-deployment
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      containers:
      - name: elk
        image: ravirdv/elk
        ports:
        - containerPort: 5044
        - containerPort: 5140
        - containerPort: 5601
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elk-svc
spec:
  ports:
  - port: 80
    targetPort: 5601
    protocol: TCP
    name: http
  - port: 5140
    targetPort: 5140
    protocol: TCP
    name: syslog
  selector:
    app: elk
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elk-ingress
spec:
  rules:
  - host: kibana.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: elk-svc
          servicePort: 80
