apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    load_module modules/ngx_http_app_protect_module.so;

    error_log /var/log/nginx/error.log debug;

    events {
        worker_connections 10240;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;

        upstream app_backend_com {
            server dvwa-svc.default.svc.cluster.local:80;
        }
        server {
            listen 80;
            server_name secure.appdeck.com;
            proxy_http_version 1.1;

            app_protect_enable on;
            app_protect_security_log_enable on;
            app_protect_security_log "/etc/nginx/log-default.json" syslog:server=elk-svc.default.svc.cluster.local:5140;

            location / {
                client_max_body_size 0;
                default_type text/html;
                # set your backend here
                proxy_pass http://app_backend_com;
                proxy_set_header Host $host;
            }
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-plus
  labels:
    app: nginx-plus
spec:
  containers:
    - name: nginx-plus
      image: your/nginx/approtect/image
      volumeMounts:
      - mountPath: /etc/nginx/nginx.conf
        readOnly: true
        name: nginx-conf
        subPath: nginx.conf
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: nginx.conf
            path: nginx.conf

  imagePullSecrets:
      - name: gcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-secure-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-plus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dvwa-secure-ingress
spec:
  rules:
  - host: secure.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dvwa-secure-svc
          servicePort: 80
