apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress-session
  annotations:
    nginx.com/sticky-cookie-services: "serviceName=tea-health-svc srv_id expires=1h path=/tea"
spec:
  rules:
  - host: session.appdeck.io
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-health-svc
          servicePort: 80
